# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo fmt --all --
        pass_filenames: true
        types: [file, rust]
        language: system
      - id: rust-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
        entry: cargo clippy --all-targets --all-features -- -Dclippy::all
        pass_filenames: false
        types: [file, rust]
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      # - id: pretty-format-json
      #   args: ["--autofix"]
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 5ba47274f9b181bce26a5150a725577f3c336011 # frozen: v3.6.2
    hooks:
      - id: prettier
        args: [--no-semi]
